Update black-linter.yml

diff --git a/.github/workflows/black-linter.yml b/.github/workflows/black-linter.yml
--- a/.github/workflows/black-linter.yml
+++ b/.github/workflows/black-linter.yml
@@ -1,6 +1,6 @@
 name: Black Formatter
 
-on: [ push, pull_request ]
+on: [push, pull_request]
 
 jobs:
   black:
@@ -22,16 +22,18 @@ jobs:
 
       - name: Check Black formatting
         run: |
-          black --check --line-length 80 . > output.log || echo "::set-output name=black_failed::true"
-        id: black_check
+          black --check --line-length 80 . > black_output.log || echo "black_failed=true" >> $GITHUB_ENV
+        shell: bash
 
       - name: Annotate code
-        if: steps.black_check.outputs.black_failed == 'true'
+        if: env.black_failed == 'true'
         run: |
-          grep -Po 'would reformat \K.*' output.log | while read file; do
+          grep -Po 'would reformat \K.*' black_output.log | while read file; do
             echo "::error file=$file,line=1,col=1::Improper formatting, please reformat."
           done
+        shell: bash
 
       - name: Fail workflow
-        if: steps.black_check.outputs.black_failed == 'true'
+        if: env.black_failed == 'true'
         run: exit 1
+        shell: bash
