Fix attempt for black-linter.yml

diff --git a/.github/workflows/black-linter.yml b/.github/workflows/black-linter.yml
--- a/.github/workflows/black-linter.yml
+++ b/.github/workflows/black-linter.yml
@@ -1,6 +1,6 @@
 name: Black Formatter
 
-on: [ push, pull_request ]
+on: [push, pull_request]
 
 jobs:
   black:
@@ -22,11 +22,11 @@ jobs:
 
       - name: Check Black formatting
         run: |
-          black --check --line-length 80 . || echo "Black formatting check failed." >> $GITHUB_ENV
+          black --check --line-length 80 . || echo "BLACK_FORMATTING_FAILED=1" >> $GITHUB_ENV
         continue-on-error: true
 
-      - name: Fail annotations
-        if: ${{ env.Black formatting check failed }}
+      - name: Create annotation if formatting fails
+        if: ${{ env.BLACK_FORMATTING_FAILED == '1' }}
         run: |
           echo "::error file=filename,line=1,col=1::Formatting check failed on the following files:"
           black --diff --line-length 80 . 2>&1 | grep -E "would reformat" | sed -E "s/would reformat //"
